export enum AuditAction {
  APPLICATION_DRAFT_CREATED = 'APPLICATION_DRAFT_CREATED',
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  APPLICATION_REVIEW_STARTED = 'APPLICATION_REVIEW_STARTED',
  APPLICATION_INFO_REQUESTED = 'APPLICATION_INFO_REQUESTED',
  APPLICATION_RESUBMITTED = 'APPLICATION_RESUBMITTED',
  APPLICATION_REVIEW_COMPLETED = 'APPLICATION_REVIEW_COMPLETED',
  APPLICATION_APPROVED = 'APPLICATION_APPROVED',
  APPLICATION_REJECTED = 'APPLICATION_REJECTED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
}
